name: Continuous Integration, bump version and merge into develop

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          yarn install
          yarn test

  bump-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses:  'phips28/gh-action-bump-version@master'
        name:  'Automated Version Bump'
        env:
          GITHUB_TOKEN: ${{ secrets.OSD_GH_TOKEN }}
  
  merge-develop:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: devmasx/merge-branch@v1.1.0
        name: Merge to develop branch
        with:
          type: now
          target_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.OSD_GH_TOKEN }}